# Export rom name
export VENDOR := psd

# PSD version info
PSD_VERSION_MAJOR := 2
PSD_VERSION_MINOR := 0
PSD_VERSION_MAINTENANCE := RC
PSD_TYPE := REMIX

# PA version info
ROM_VERSION_MAJOR := 4
ROM_VERSION_MINOR := 5
ROM_VERSION_MAINTENANCE := 
ROM_VERSION_TAG := BETA1
