# Export rom name
export VENDOR := psd

# PSD version info
PSD_VERSION_MAJOR := 3
PSD_VERSION_MINOR := 0
PSD_VERSION_MAINTENANCE := normal
PSD_TYPE := REMIX
PSD_VERSION_TAG := ALPHA1

# PA version info
PA_VERSION_MAJOR := 5
PA_VERSION_MINOR := 0
PA_VERSION_MAINTENANCE := normal 
PA_VERSION_TAG := ALPHA1
