# Export rom name
export VENDOR := psd

# PSD version info
PSD_VERSION_MAJOR := 3
PSD_VERSION_MINOR := 5.9.7
PSD_VERSION_MAINTENANCE :=
PSD_TYPE := darkobas
PSD_VERSION_TAG := BETA

# PA version info
PA_VERSION_MAJOR := 5
PA_VERSION_MINOR := 0
PA_VERSION_MAINTENANCE :=
PA_VERSION_TAG := ALPHA
