ifneq ($PSD_VERSION_TAG,"")
        PSD_VERSION := $(PSD_VERSION_MAJOR).$(PSD_VERSION_MINOR).$(PSD_VERSION_MAINTENANCE)-$(PSD_VERSION_TAG)
else
        PSD_VERSION := $(PSD_VERSION_MAJOR).$(PSD_VERSION_MINOR).$(PSD_VERSION_MAINTENANCE)
endif

export BUILD_DATE := $(shell date -u +%Y%m%d)
export PSD_VERSION := $(PSD_VERSION)-$(BUILD_DATE)
